FROM node:20

RUN npm install -g npm@11.4.1

WORKDIR /app

COPY ../testflow-ui-forge/package*.json ./
RUN npm install

COPY ../testflow-ui-forge .

# Mở cổng (nếu ứng dụng cần)
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
